config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :sponsors
  resources :settings
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }, via: :get
  end

  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
  end

  namespace :pages do
    get "allpodcasts"
    get "locations"
    get "platforms"
    get "timeofday"
    get "downloads"
  end

  resources :abouts
  resources :privacies
  resources :terms
  resources :episodes
  get 'pending' => 'episodes#pending', as: :pending
  resources :podcasts
  get 'search' => 'search#search'
  get 'shows/acp' => redirect('/podcasts/acp')
  get 'shows/boomaddiction' => redirect('/podcasts/ba')
  get 'shows/cbw' => redirect('/podcasts/cbw')
  get 'shows/collectingvaliant' => redirect('/podcasts/cv')
  get 'shows/iamgotham' => redirect('/podcasts/iag')
  get 'shows/nerdylegion' => redirect('/podcasts/nl')
  get 'shows/pth' => redirect('/podcasts/pth')
  get 'shows/rb' => redirect('/podcasts/rb')
  get 'podcasts/rb' => redirect('/podcasts/absolutedc')
  get 'podcasts/pth' => redirect('/podcasts/wrestlinginsomniac')
  get 'shows/marvelpodcast' => redirect('/podcasts/ump')
  get 'shows/vcp' => redirect('/podcasts/vcp')
  get 'shows/whatdidyouwatchthisweek' => redirect('/podcasts/wdyw')
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callback" }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  root :to => 'episodes#index'
  get "aboutus" => 'abouts#index', as: :aboutus
  get 'privacy' => 'privacies#index', as: :privacypolicy
  get 'terms' => 'terms#index', as: :termsofservice
  get 'subscribe' => 'pages#subscribe', as: :subscribe
  get 'user_admin' => 'pages#user_admin', as: :user_admin
  get 'user_admin_new_path' => 'pages#user_admin_new', as: :user_admin_new
  resource :pages do
    member do
      post :create_user
      post :destroy_user
      post :podcaster_true
      post :podcaster_false
      post :analytics_true
      post :analytics_false
      post :admin_true
      post :admin_false
    end
  end
  get 'analytics' => 'pages#analytics', as: :analytics
  get 'sitemap.xml', :to => 'pages#sitemap', :defaults => { :format => 'xml' }
  get 'robots.:format' => 'pages#robots'
  get '*path' => redirect('/')
end

app/models/episode.rb
class Episode < ApplicationRecord
  extend FriendlyId
	friendly_id :path, use: [:slugged, :finders]
  belongs_to :podcast
  before_validation :clean_up_status
  mount_uploader :audiourl, EpisodeUploader
  process_in_background :audiourl
  validates_presence_of :podcast_id, :episode, :title, :description, :published_on, :status, :episodetype, :audiourl
  after_create :update_slug, on: :create

  def update_slug
    unless slug.include? self.path.to_s
      self.slug = nil
      self.save
    end
  end

  def clean_up_status
    self.published_on = case status
                        when "Draft"
                          created_at
                        else
                          published_on
                        end
    true
  end

  def schedule
    if self.status == "Scheduled"
      begin
      	ScheduleJob.set(wait_until: published_on).perform_later(self)
      rescue Exception => e
      	self.update_attributes(status: "Scheduling-error")
      end
    else
      publish
    end
  end

  def publish
    unless self.status == "Draft"
    	begin
        if Rails.env.production?
          twitter = Twitter::REST::Client.new do |config|
            config.consumer_key        = ENV['TWITTER_KEY']
            config.consumer_secret     = ENV['TWITTER_SECRET']
            config.access_token        = ENV['TWITTER_TOKEN']
            config.access_token_secret = ENV['TWITTER_TOKEN_SECRET']
          end
          if self.podcast.twitter?
            if self.podcast.user2_id? && self.podcast.user3_id?
              twitter.update("Just posted @" + self.podcast.twitter.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + ", @" + User.find(self.podcast.user2_id).twitter.to_s + " & @" + User.find(self.podcast.user3_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            elsif self.podcast.user2_id?
              twitter.update("Just posted @" + self.podcast.twitter.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + " & @" + User.find(self.podcast.user2_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            else
              twitter.update("Just posted @" + self.podcast.twitter.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            end
          else
            if self.podcast.user2_id? && self.podcast.user3_id?
              twitter.update("Just posted " + self.podcast.title.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + ", @" + User.find(self.podcast.user2_id).twitter.to_s + " & @" + User.find(self.podcast.user3_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            elsif self.podcast.user2_id?
              twitter.update("Just posted " + self.podcast.title.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + " & @" + User.find(self.podcast.user2_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            else
              twitter.update("Just posted " + self.podcast.title.to_s + ": " + self.title.to_s.titleize + " with @" + User.find(self.podcast.user_id).twitter.to_s + " https://nerdylegion.com/episodes/" + self.slug.to_s)
            end
          end
        end
        self.update_attributes(status: "Published")
      rescue Exception => e
        puts "!!!!!!!!!!!!!!!#{e.message}!!!!!!!!!!!!!!!"
        self.update_attributes(status: "Publishing-error")
    	end
    end
  end

  def slug_candidates
    [ :path ]
  end

end

app/controllers/episodes_controller.rb
require 'open-uri'

class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :pending]

  # GET /episodes
  # GET /episodes.json
  def index
    if request.format.rss?
      @episodes = Episode.where(status: "Published").where(published_on: (DateTime.now - 30.days)..(DateTime.now)).limit(50).order(published_on: :desc)
    elsif request.format.json?
      @episodes = Episode.where(status: "Published").where(published_on: (DateTime.now - 30.days)..(DateTime.now)).limit(100).order(published_on: :desc)
    else
      @episodes = Episode.where(status: "Published").where(published_on: (DateTime.now - 8.days)..(DateTime.now)).order(published_on: :desc)
    end
  end

  def pending
    @episodes = Episode.where.not(status: "Published").order(published_on: :asc)
  end
  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @sponsors = Sponsor.where(status: true)
    @host = User.where(id: @episode.podcast.user_id)
    @host2 = User.where(id: @episode.podcast.user2_id)
    @host3 = User.where(id: @episode.podcast.user3_id)
    if user_signed_in?
      if current_user.admin?
        @previous = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode - 1).first
        @next = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode + 1).first
        unless user_signed_in? && current_user.podcaster?
          ahoy.track "#{@episode.podcast.title.to_s}", episode: "#{@episode.episode.to_s}", title: "#{@episode.title.to_s}", value: "#{@episode.podcast.title.to_s} Ep #{@episode.episode.to_s}"
        end
      elsif current_user.id == @episode.podcast.user_id || @episode.podcast.user2_id || @episode.podcast.user3_id || @episode.podcast.producer_id
        @previous = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode - 1).first
        @next = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode + 1).first
        unless user_signed_in? && current_user.podcaster?
          ahoy.track "#{@episode.podcast.title.to_s}", episode: "#{@episode.episode.to_s}", title: "#{@episode.title.to_s}", value: "#{@episode.podcast.title.to_s} Ep #{@episode.episode.to_s}"
        end
      else
        if @episode.status == "Scheduled"
          redirect_to root_url
          flash[:error] = "This episode of " + @episode.podcast.title.to_s + " won't be available until " + @episode.published_on.strftime("%b %m, %Y")
        elsif @episode.status == "Draft"
          redirect_to root_url
          flash[:error] = "This episode cannot be viewed until published!"
        else
          @previous = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode - 1).first
          @next = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode + 1).first
          unless user_signed_in? && current_user.podcaster?
            ahoy.track "#{@episode.podcast.title.to_s}", episode: "#{@episode.episode.to_s}", title: "#{@episode.title.to_s}", value: "#{@episode.podcast.title.to_s} Ep #{@episode.episode.to_s}"
          end
        end
      end
    else
      if @episode.status == "Scheduled"
        redirect_to root_url
        flash[:error] = "This episode of " + @episode.podcast.title.to_s + " won't be available until " + @episode.published_on.strftime("%b %m, %Y")
      elsif @episode.status == "Draft"
        redirect_to root_url
        flash[:error] = "This episode cannot be viewed until published!"
      else
        @previous = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode - 1).first
        @next = Episode.where(podcast_id: @episode.podcast.id).where(status: "Published").where(episode: @episode.episode + 1).first
        unless user_signed_in? && current_user.podcaster?
          ahoy.track "#{@episode.podcast.title.to_s}", episode: "#{@episode.episode.to_s}", title: "#{@episode.title.to_s}", value: "#{@episode.podcast.title.to_s} Ep #{@episode.episode.to_s}"
        end
      end
    end
  end

  # GET /episodes/new
  def new
    if user_signed_in? && current_user.podcaster?
      @episode = Episode.new
      @podcast = Podcast.where(status: "Published")
    else
      redirect_to root_url
    end
  end

  # GET /episodes/1/edit
  def edit
    @podcast = Podcast.where(status: "Published")
  end

  # POST /episodes
  # POST /episodes.json
  def create
    if user_signed_in? && current_user.podcaster?
      @episode = Episode.new(episode_params)
      @podcast = Podcast.where(status: "Published").order(title: :asc)
      respond_to do |format|
        if @episode.save
          @episode.update_attributes(download_size: @episode.audiourl.size.to_i/1024/1000)
          @episode.update_attributes(duration: Time.at(@episode.audiourl.size.to_i/1024*8.2/64).utc.strftime('%H:%M:%S'))
          @episode.schedule
          format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
          format.json { render :json => @episode }
        else
          format.html { render :new }
          format.json { render json: @episode.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:podcast_id, :episode, :title, :description, :shownotes, :published_on, :status, :path, :audio, :audiourl, :download_size, :duration, :itunestype, :episodetype, :explicit)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
  def status_for(episode)
    if episode.published_on?
      if episode.published_on > Time.zone.now
        "Scheduled"
      else
        "Published"
      end
    else
      "Draft"
    end
  end
end

app/views/episodes/edit.html.erb
<div class="container">
	<div class="col-md-10 col-md-offset-1 outline">
		<%= render 'form', episode: @episode %>
	</div>
</div>

app/views/episodes/index.amp.erb
<% @episodes.each do |e| %>
          <%= link_to e, title: e.podcast.title + " Ep " + e.episode.to_s + ": " +  e.title.titleize do %>
            <amp-img src='<%= e.podcast.logo.url(:small) %>' alt='<%= e.podcast.title %>' height='200' width='200' layout="responsive"></amp-img>
          <% end %>
          <h2>
            <%= link_to e, title: e.podcast.title + "Ep " + e.episode.to_s + ": " + e.title.titleize.to_s do %>
              <%= e.podcast.title %> Ep <%= e.episode %>: <%= e.title.titleize %>
            <% end %>
          </h2>
          <h5>Published <%= e.published_on.strftime("%b %d, %Y")%>
                                <% if e.audiourl? %>
                                  (<%= ((Mechanize.new.head( URI.join("https:", e.audiourl.to_s) )["content-length"].to_i)/1024/1000) %> MB)
                                <% end %></h5>
          <p>
            <%= sanitize e.description.html_safe, scrubber: AmpScrubber.new %>
          </p>
          <amp-audio controls>
            <source src="<%= e.audiourl.to_s.gsub("http://", "https://") %>" type="audio/mp3">
          </amp-audio>
          <p>
            <button>
              <%= link_to e, title: e.podcast.title + " Ep " + e.episode.to_s + ": " +  e.title.titleize do %>Read More<% end %>
            </button>
          </p>
          <br />
<% end %>

app/views/episodes/index.html.erb
<div class="col-md-12 box">
  <div class="col-md-9 col-sm-9">
    <% @episodes.each do |e| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="body-header"><%= link_to e.podcast, title: e.podcast.title.titleize do %><%= e.podcast.title.titleize %><% end %></h2>
          </div>
          <div class="panel-body">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <span class="pull-left hidden-xs">
                <%= link_to e, title: e.podcast.title + " Ep " + e.episode.to_s + ": " +  e.title.titleize do %>
                  <%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/loading.gif", data: { src: e.podcast.logourl.small.to_s }, alt: e.podcast.title, class: "img-responsive", width: "90%;" %>
                <% end %>
              </span>
              <h3 class="body-header" style="padding-bottom: 10px !important;">
                <%= link_to e, title: e.title.titleize.to_s do %>
                  <% if e.episodetype == "Bonus" %>BONUS:<% end %> <%= e.title.titleize %>
                <% end %>
              </h3>
              <span class="pull-left visible-xs" style="width: 100px !important;">
                <%= link_to e, title: e.podcast.title + " Ep " + e.episode.to_s + ": " +  e.title.titleize do %>
                  <%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/loading.gif", data: { src: e.podcast.logourl.small.to_s }, alt: e.podcast.title, class: "img-responsive", width: "90%;" %>
                <% end %>
              </span>
              <p class="pull-left">
                <%= e.description.html_safe %>
              </p>
              <div class="cleafix"></div>
            </div>
          </div>
          <div class="panel-footer">
            <ul class="list-inline">
              <% if e.download_size? %>
                <li>
                  <%= link_to e.audiourl.to_s, title: "Download MP3", class: "track_downloads", data: { podcast: e.podcast.title.to_s, episode: e.episode.to_s, title: e.title.to_s, value: e.podcast.title.to_s + " Ep " + e.episode.to_s } do %>
                    <i class="fa fa-download"></i> Download (<%= e.download_size.to_s %> MB)</li>
                  <% end %>
              <% end %>
              <% if e.duration? %>
                <li>
                  <i class="fa fa-clock-o"></i> <%= e.duration.to_s %>
                </li>
              <% end %>
              <li><i class="fa fa-calendar"></i> <%= e.published_on.strftime("%b %d, %Y") %></li>
              <% if user_signed_in? && current_user.podcaster? %>
                <% if current_user.admin? %>
                  <li><i class="fa fa-edit"></i>
                    <%= link_to edit_episode_path(e.id),
                              title: "Edit episode" do %>
                              Edit
                    <% end %>
                  </li>
                  <li><i class="fa fa-remove"></i>
                    <%= link_to episode_path(e.id),
                              method: :delete,
                              data: { confirm: "Are you sure you want to delete this episode?" },
                              title: "Delete episode" do %>
                              Delete
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <% if current_user.id == e.podcast.user_id %>
                      <%= link_to edit_episode_path(e.id),
                                title: "Edit episode" do %>
                                <i class="fa fa-edit"></i> Edit
                      <% end %>
                    <% end %>
                    <% if current_user.id == e.podcast.user2_id %>
                      <%= link_to edit_episode_path(e.id),
                                title: "Edit episode" do %>
                                <i class="fa fa-edit"></i> Edit
                      <% end %>
                    <% end %>
                    <% if current_user.id == e.podcast.user3_id %>
                      <%= link_to edit_episode_path(e.id),
                                title: "Edit episode" do %>
                                <i class="fa fa-edit"></i> Edit
                      <% end %>
                    <% end %>
                    <% unless current_user.id == e.podcast.user_id && e.podcast.producer_id %>
                      <% if current_user.id == e.podcast.producer_id %>
                        <%= link_to edit_episode_path(e.id),
                                  title: "Edit episode" do %>
                                  <i class="fa fa-edit"></i> Edit
                        <% end %>
                      <% end %>
                    <% end %>
                  </li>
                  <li>
                    <% if current_user.id == e.podcast.user_id %>
                      <%= link_to episode_path(e.id),
                                method: :delete,
                                data: { confirm: "Are you sure you want to delete this episode?" },
                                title: "Delete episode" do %>
                                <i class="fa fa-remove"></i> Delete
                      <% end %>
                    <% end %>
                    <% if current_user.id == e.podcast.user2_id %>
                      <%= link_to episode_path(e.id),
                                method: :delete,
                                data: { confirm: "Are you sure you want to delete this episode?" },
                                title: "Delete episode" do %>
                                <i class="fa fa-remove"></i> Delete
                      <% end %>
                    <% end %>
                    <% if current_user.id == e.podcast.user3_id %>
                      <%= link_to episode_path(e.id),
                                method: :delete,
                                data: { confirm: "Are you sure you want to delete this episode?" },
                                title: "Delete episode" do %>
                                <i class="fa fa-remove"></i> Delete
                      <% end %>
                    <% end %>
                    <% unless current_user.id == e.podcast.user_id && e.podcast.producer_id %>
                      <% if current_user.id == e.podcast.producer_id %>
                        <%= link_to episode_path(e.id),
                                  method: :delete,
                                  data: { confirm: "Are you sure you want to delete this episode?" },
                                  title: "Delete episode" do %>
                                  <i class="fa fa-remove"></i> Delete
                        <% end %>
                      <% end %>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
  </div>
  <%= render "pages/sidebar" %>
</div>

app/views/episodes/new.html.erb
<div class="container">
	<div class="col-md-10 col-md-offset-1 outline">
		<%= render 'form', episode: @episode %>
	</div>
</div>

app/views/episodes/pending.html.erb
<% if @episodes.count > 0 %>
  <div class="col-md-12">
    <table class="table table-responsive table-condensed table-striped">
      <thead>
        <tr>
          <td>Logo</td>
          <td>Podcast</td>
          <td>Episode</td>
          <td>Title</td>
          <td>Created</td>
          <td>Scheduled Date</td>
          <td>Status</td>
          <td></td>
          <td class="text-center">Actions</td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <% @episodes.each do |e| %>
          <% if e.podcast.user_id == current_user.id || e.podcast.user2_id == current_user.id || e.podcast.user3_id == current_user.id || e.podcast.producer_id == current_user.id || current_user.admin? %>
            <tr>
              <td><%= image_tag e.podcast.logourl.thumb.to_s, width: "25px", alt: e.podcast.title %></td>
              <td><%= e.podcast.title %></td>
              <td><%= e.episode.to_s %></td>
              <td><%= e.title %></td>
              <% if e.created_at? %>
                <td><%= e.created_at.strftime("%B %d, %Y") %></td>
              <% else %>
                <td>N/A</td>
              <% end %>
              <% if e.published_on? %>
                <td><%= e.published_on.strftime("%B %d, %Y %H:%M") %></td>
              <% else %>
                <td>N/A</td>
              <% end %>
              <td><%= e.status %></td>
              <td class="text-right"><%= link_to "View", episode_path(e.slug) %></td>
              <td class="text-center"><%= link_to "Edit", edit_episode_path(e.slug) %></td>
              <td class="text-right"><%= link_to "Delete", episode_path(e.slug), method: :delete %></td>
            </tr>
          <% else %>
          <tr>
            <td><%= image_tag e.podcast.logourl.thumb.to_s, width: "25px", alt: e.podcast.title %></td>
            <td><%= e.podcast.title %></td>
            <td><%= e.episode.to_s %></td>
            <td><%= e.title %></td>
            <% if e.created_at? %>
              <td><%= e.created_at.strftime("%B %d, %Y") %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
            <% if e.published_on? %>
              <td><%= e.published_on.strftime("%B %d, %Y %H:%M") %></td>
            <% else %>
              <td>N/A</td>
            <% end %>
            <td><%= e.status %></td>
            <td class="text-right"></td>
            <td class="text-center">N/A</td>
            <td class="text-right"></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="col-md-12">
    <h3>No drafts or posts scheduled</h3>
  </div>
<% end %>