config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :sponsors
  resources :settings
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }, via: :get
  end

  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
  end

  namespace :pages do
    get "allpodcasts"
    get "locations"
    get "platforms"
    get "timeofday"
    get "downloads"
  end

  resources :abouts
  resources :privacies
  resources :terms
  resources :episodes
  get 'pending' => 'episodes#pending', as: :pending
  resources :podcasts
  get 'search' => 'search#search'
  get 'shows/acp' => redirect('/podcasts/acp')
  get 'shows/boomaddiction' => redirect('/podcasts/ba')
  get 'shows/cbw' => redirect('/podcasts/cbw')
  get 'shows/collectingvaliant' => redirect('/podcasts/cv')
  get 'shows/iamgotham' => redirect('/podcasts/iag')
  get 'shows/nerdylegion' => redirect('/podcasts/nl')
  get 'shows/pth' => redirect('/podcasts/pth')
  get 'shows/rb' => redirect('/podcasts/rb')
  get 'podcasts/rb' => redirect('/podcasts/absolutedc')
  get 'podcasts/pth' => redirect('/podcasts/wrestlinginsomniac')
  get 'shows/marvelpodcast' => redirect('/podcasts/ump')
  get 'shows/vcp' => redirect('/podcasts/vcp')
  get 'shows/whatdidyouwatchthisweek' => redirect('/podcasts/wdyw')
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callback" }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  root :to => 'episodes#index'
  get "aboutus" => 'abouts#index', as: :aboutus
  get 'privacy' => 'privacies#index', as: :privacypolicy
  get 'terms' => 'terms#index', as: :termsofservice
  get 'subscribe' => 'pages#subscribe', as: :subscribe
  get 'user_admin' => 'pages#user_admin', as: :user_admin
  get 'user_admin_new_path' => 'pages#user_admin_new', as: :user_admin_new
  resource :pages do
    member do
      post :create_user
      post :destroy_user
      post :podcaster_true
      post :podcaster_false
      post :analytics_true
      post :analytics_false
      post :admin_true
      post :admin_false
    end
  end
  get 'analytics' => 'pages#analytics', as: :analytics
  get 'sitemap.xml', :to => 'pages#sitemap', :defaults => { :format => 'xml' }
  get 'robots.:format' => 'pages#robots'
  get '*path' => redirect('/')
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  mount_uploader :image, SponsorUploader
  validates_presence_of :name, :description, :image, :link
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    if user_signed_in? && current_user.admin?
      @sponsors = Sponsor.all
    else
      redirect_to root_url
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    redirect_to root_url unless user_signed_in? && current_user.admin?
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: 'Sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:name, :description, :link, :image, :status)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<div class="col-md-12">
  <%= simple_form_for(@sponsor) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <ul class="list-inline">
        <li class="col-md-8 col-sm-8 col-xs-12">
          <label name="name">* Sponsor Name</label>
          <%= f.input :name, label: false, placeholder: "Enter sponsor name", class: "form-control" %>
        </li>
        <li class="col-md-4 col-sm-4 col-xs-12">
          <label name="image">* Upload Image</label>
          <%= f.file_field :image %>
        </li>
      </ul>
      <div class="clearfix"></div>
      <label name="description">* Description</label>
      <%= f.input :description, label: false, as: :trix_editor, class: "form-control" %>
      <small>Your sponsor description will appear in your episode show page, RSS feeds, and on podcast players.</small>
      <div class="clearfix"><br /></div>
      <ul class="list-inline">
        <li class="col-md-10 col-sm-10 col-xs-12">
          <%= f.input :link, placeholder: "Enter sponsor or affiliate link", class: "form-control" %>
        </li>
        <li class="col-md-2 col-sm-2 col-xs-12 text-center">
          <label name="status">Active?</label>
          <%= f.input :status, class: "form-control", label: false %>
        </li>
      </ul>
    </div>

    <div class="clearfix"><br /></div>
    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary col-md-12 col-sm-12 col-xs-12" %>
    </div>

  <% end %>
  <div class="clearfix"><br /><br /></div>

</div>

app/views/sponsors/edit.html.erb
<div class="col-md-12 col-sm-12 col-xs-12 panel panel-default">
  <br />
  <h4>Editing Sponsor</h4>

  <%= render 'form', sponsor: @sponsor %>
</div>

app/views/sponsors/index.html.erb
<div class="col-md-12 box">
  <div class="col-md-9 col-sm-9 panel panel-default">
    <h4>Sponsors <div class="pull-right"><%= link_to 'New Sponsor', new_sponsor_path, class: "btn btn-primary btn-sm" %></div></h4>
    <table class="table table-responsive table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Link</th>
          <th>Image</th>
          <th>Active</th>
          <th class="text-center">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @sponsors.each do |sponsor| %>
          <tr>
            <td><h4 class="body-header"><%= sponsor.name.to_s %></h4></td>
            <td><%= link_to "Link", sponsor.link.to_s, title: sponsor.name.to_s %></td>
            <td><%= image_tag sponsor.image.thumb.to_s, alt: sponsor.name.to_s, class: "img-responsive" %></td>
            <td><%= sponsor.status.to_s %></td>
            <td class="text-center">
              <%= link_to 'Show', sponsor, class: "btn btn-primary btn-sm" %>
              <%= link_to 'Edit', edit_sponsor_path(sponsor), class: "btn btn-primary btn-sm"  %>
              <%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm"  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br />
  </div>
  <%= render "pages/sidebar" %>
</div>

app/views/sponsors/new.html.erb
<div class="col-md-12 col-sm-12 col-xs-12 panel panel-default">
  <br />
  <h4>New Sponsor</h4>

  <%= render 'form', sponsor: @sponsor %>
</div>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @sponsor.image.to_s, alt: @sponsor.name.to_s %>

<p>
  <strong>Name:</strong>
  <%= @sponsor.name.to_s %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sponsor.description.to_s.html_safe %>
</p>

<p>
  <strong>Link:</strong>
  <%= @sponsor.link.to_s %>
</p>

<p>
  <strong>Active?</strong>
  <%= @sponsor.status.to_s %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>