config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :sponsors
  resources :settings
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }, via: :get
  end

  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
  end

  namespace :pages do
    get "allpodcasts"
    get "locations"
    get "platforms"
    get "timeofday"
    get "downloads"
  end

  resources :abouts
  resources :privacies
  resources :terms
  resources :episodes
  get 'pending' => 'episodes#pending', as: :pending
  resources :podcasts
  get 'search' => 'search#search'
  get 'shows/acp' => redirect('/podcasts/acp')
  get 'shows/boomaddiction' => redirect('/podcasts/ba')
  get 'shows/cbw' => redirect('/podcasts/cbw')
  get 'shows/collectingvaliant' => redirect('/podcasts/cv')
  get 'shows/iamgotham' => redirect('/podcasts/iag')
  get 'shows/nerdylegion' => redirect('/podcasts/nl')
  get 'shows/pth' => redirect('/podcasts/pth')
  get 'shows/rb' => redirect('/podcasts/rb')
  get 'podcasts/rb' => redirect('/podcasts/absolutedc')
  get 'podcasts/pth' => redirect('/podcasts/wrestlinginsomniac')
  get 'shows/marvelpodcast' => redirect('/podcasts/ump')
  get 'shows/vcp' => redirect('/podcasts/vcp')
  get 'shows/whatdidyouwatchthisweek' => redirect('/podcasts/wdyw')
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callback" }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  root :to => 'episodes#index'
  get "aboutus" => 'abouts#index', as: :aboutus
  get 'privacy' => 'privacies#index', as: :privacypolicy
  get 'terms' => 'terms#index', as: :termsofservice
  get 'subscribe' => 'pages#subscribe', as: :subscribe
  get 'user_admin' => 'pages#user_admin', as: :user_admin
  get 'user_admin_new_path' => 'pages#user_admin_new', as: :user_admin_new
  resource :pages do
    member do
      post :create_user
      post :destroy_user
      post :podcaster_true
      post :podcaster_false
      post :analytics_true
      post :analytics_false
      post :admin_true
      post :admin_false
    end
  end
  get 'analytics' => 'pages#analytics', as: :analytics
  get 'sitemap.xml', :to => 'pages#sitemap', :defaults => { :format => 'xml' }
  get 'robots.:format' => 'pages#robots'
  get '*path' => redirect('/')
end

app/views/pages/_sidebar.html.erb
<div class="col-md-3 col-sm-3 visible-lg visible-md visible-sm">
  <% if controller_name == "episodes" && action_name == "show" %>
    <h4>About This Show</h4>
    <%= @episode.podcast.description.to_s.html_safe %>
    <h4>Hosted By</h4>
    <% @host.each do |host| %>
      <p><% if host.imageurl? %><%= image_tag host.imageurl.thumb.to_s, alt: host.name.to_s, width: "25px;" %><% else %><%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/nouserlogo.gif", alt: host.name.to_s, width: "25px;" %><% end %> <%= link_to "https://www.twitter.com" + host.twitter.to_s, title: host.name.to_s do %><%= host.name.to_s %><% end %></p>
    <% end %>
    <% @host2.each do |host2| %>
      <p><% if host2.imageurl? %><%= image_tag host2.imageurl.thumb.to_s, alt: host2.name.to_s, width: "25px;" %><% else %><%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/nouserlogo.gif", alt: host2.name.to_s, width: "25px;" %><% end %> <%= link_to "https://www.twitter.com" + host2.twitter.to_s, title: host2.name.to_s do %><%= host2.name.to_s %><% end %></p>
    <% end %>
    <% @host2.each do |host3| %>
      <% if host3.imageurl? %><%= image_tag host3.imageurl.thumb.to_s, alt: host3.name.to_s, width: "25px;" %><% else %><%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/nouserlogo.gif", alt: host3.name.to_s, width: "25px;" %><% end %> <%= link_to "https://www.twitter.com" + host3.twitter.to_s, title: host3.name.to_s do %><%= host3.name.to_s %><% end %>
    <% end %>
    <h4>Subscribe Now</h4>
    <ul class="list-unstyled subscribe-buttons">
      <% if @episode.podcast.itunes? %>
        <li><%= link_to @episode.podcast.itunes, target: "_blank", rel: "noopener", title: "Apple Podcasts" do %>
          Via Apple Podcasts<% end %></li>
      <% end %>
      <% if @episode.podcast.google? %>
        <li><%= link_to @episode.podcast.google, target: "_blank", rel: "noopener", title: "Google Play" do %>
          Via Google Play<% end %></li>
      <% end %>
      <% if @episode.podcast.spotify? %>
        <li><%= link_to @episode.podcast.spotify, target: "_blank", rel: "noopener", title: "Spotify" do %>
          Via Spotify<% end %></li>
      <% end %>
      <% if @episode.podcast.stitcher? %>
        <li><%= link_to @episode.podcast.stitcher, target: "_blank", rel: "noopener", title: "Stitcher" do %>
          Via Stitcher<% end %></li>
      <% end %>
      <% if @episode.podcast.tunein? %>
        <li><%= link_to @episode.podcast.tunein, target: "_blank", rel: "noopener", title: "TuneIn" do %>
          Via TuneIn<% end %></li>
      <% end %>
      <% if @episode.podcast.youtube? %>
        <li><%= link_to @episode.podcast.youtube, target: "_blank", rel: "noopener", title: "YouTube" do %>
          Via YouTube<% end %></li>
      <% end %>
      <li><%= link_to root_url + "podcasts/" + @episode.podcast.slug.to_s + ".rss", title: "RSS" do %>
        Via RSS<% end %></li>
    </ul>
  <% else %>
    <% if Sponsor.count > 0 %>
      <h4>Brought To You By</h4>
      <% Sponsor.all.each do |sponsor| %>
        <%= link_to sponsor.link.to_s, target: "_blank", rel: "noopener", title: sponsor.name.to_s + ", " + strip_tags(sponsor.description.to_s.html_safe) do %>
          <%= image_tag sponsor.image.large.to_s, alt: sponsor.name.to_s, class: "img-responsive" %>
        <% end %>
        <br />
      <% end %>
    <% else %>
      <h4>Brought To You By</h4>
      <%= link_to "https://github.com/ferrettim/nerdylegion", target: "_blank", rel: "noopener", title: "Learn more about Sprout" do %>
        <%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/sprout.jpg", alt: "Sprout", class: "img-responsive", width: "200px" %>
      <% end %>
      <br />
      <p>Sprout is a free and open source platform for creating and hosting podcasts, making it as simple and easy to use as possible.</p>
    <% end %>
  <% end %>
</div>

app/views/pages/analytics.html.erb
<% meta_title "Analytics | The Nerdy Legion Podcast Network" %>

<div class="col-md-12">
  <div class="col-md-12">
    <%= form_tag "", :method => 'get', :role => "select", class: "form-inline" do %>
      <div class="col-md-9">
        <select name="name" class="form-control" style="width: 100% !important;">
          <option value="">All Podcasts</option>
          <% @optionstitle.each do |p| %>
            <% if params[:name] == p.title.to_s %>
              <option value="<%= p.title.to_s %>" selected="<%= p.title.to_s %>"><%= p.title.to_s %></option>
            <% else %>
              <option value="<%= p.title.to_s %>"><%= p.title.to_s %></option>
            <% end %>
          <% end %>
        </select>
      </div>
      <div class="col-md-3">
        <button type="submit" class="btn btn-primary" style="width: 100% !important;">Filter Results</button>
      </div>
    <% end %>
    <div class="clearfix"><hr /></div>

<% if params[:name].present? %>

<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="body-header text-center">Average/Episode</h3>
      <h4 class="stat-header text-center">
        <% if @podcast.average > 0 %>
          <%= @podcast.average %>
        <% else %>
          No Data
        <% end %>
      </h4>
      <h5 class="percent-header text-center">
        Based on monthly numbers
      </h5>
    </div>
  </div>
</div>
<div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="body-header text-center">Today</h3>
      <h4 class="stat-header text-center">
        <%= @podcast.today %>
        <% if @podcast.today? %>
          <% if @podcast.today > @podcast.yesterday %>
            <i class="green-arrow fa fa-arrow-up"></i>
          <% else %>
            <i class="red-arrow fa fa-arrow-down"></i>
          <% end %>
        <% end %>
      </h4>
      <h5 class="percent-header text-center">
        <% if @podcast.yesterday == 0 %>
          No data for yesterday
        <% else %>
          <%= ((@podcast.today.to_f / @podcast.yesterday.to_f) * 100.0).round(2) %>% yesterday
        <% end %>
      </h5>
    </div>
  </div>
</div>
  <div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="body-header text-center">Past 7 Days</h3>
      <h4 class="stat-header text-center">
        <%= @podcast.thisweek %>
        <% if @podcast.thisweek? %>
          <% if @podcast.thisweek > @podcast.lastweek %>
            <i class="green-arrow fa fa-arrow-up"></i>
          <% else %>
            <i class="red-arrow fa fa-arrow-down"></i>
          <% end %>
        <% end %>
      </h4>
      <h5 class="percent-header text-center">
        <% if @podcast.lastweek == 0 %>
          No data for last week
        <% else %>
          <%= ((@podcast.thisweek.to_f / @podcast.lastweek.to_f) * 100.0).round(2) %>% last week
        <% end %>
      </h5>
    </div>
  </div>
</div>
  <div class="col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <h3 class="body-header text-center">Past 30 Days</h3>
      <h4 class="stat-header text-center">
        <%= @podcast.thismonth %>
        <% if @podcast.thismonth? %>
          <% if @podcast.thismonth > @podcast.lastmonth %>
            <i class="green-arrow fa fa-arrow-up"></i>
          <% else %>
            <i class="red-arrow fa fa-arrow-down"></i>
          <% end %>
        <% end %>
      </h4>
      <h5 class="percent-header text-center">
        <% if @podcast.lastmonth == 0 %>
          No data for last month
        <% else %>
          <%= ((@podcast.thismonth.to_f / @podcast.lastmonth.to_f) * 100.0).round(2) %>% last month
        <% end %>
      </h5>
    </div>
  </div>
</div>

  <br />
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="body-header">Platforms</h3>
      </div>
      <div class="panel-body">
        <%= pie_chart pages_platforms_path(name: @podcast.title), donut: true, legend: "bottom", messages: {empty: "No available data. Please check back later."}, adapter: "google", defer: true %>
      </div>
    </div>
  </div>

  <br />
  <div class="col-md-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="body-header">Time of Day Distribution</h3>
      </div>
      <div class="panel-body">
        <%= column_chart pages_timeofday_path(name: @podcast.title), messages: {empty: "No available data. Please check back later."}, defer: true %>
      </div>
    </div>
  </div>

  <br />
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="body-header">Top Episodes (Past 7 Days)</h3>
      </div>
      <div class="panel-body">
        <ol>
          <% Episode.where(podcast_id: @podcast.id).where(status: "Published").order(thisweek: :desc).limit(5).each do |e| %>
            <li style="margin-left: -20px;">
              <div class="col-md-11">
                <strong><small><%= link_to e.title.to_s, e, title: e.title.to_s %></small></strong>
              </div>
              <div class="col-md-1">
                <strong><small><%= e.thisweek.to_s %></small></strong>
              </div>
            </li>
            <div class="clearfix"></div>
          <% end %>
        </ol>
      </div>
    </div>
  </div>

  <br />
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="body-header">Top Episodes (Past 30 Days)</h3>
      </div>
      <div class="panel-body">
        <ol>
          <% Episode.where(podcast_id: @podcast.id).where(status: "Published").order(thismonth: :desc).limit(5).each do |e| %>
            <li style="margin-left: -20px;">
              <div class="col-md-11">
                <strong><small><%= link_to e.title.to_s, e, title: e.title.to_s %></small></strong>
              </div>
              <div class="col-md-1">
                <strong><small><%= e.thismonth.to_s %></small></strong>
              </div>
            </li>
            <div class="clearfix"></div>
          <% end %>
        </ol>
      </div>
    </div>
  </div>

  <br />
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="body-header">Locations</h3>
      </div>
      <div class="panel-body">
        <%= geo_chart pages_locations_path(name: @podcast.title), messages: {empty: "No available data. Please check back later."}, defer: true %>
      </div>
    </div>
  </div>

    <br />
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3 class="body-header text-center">Unique Listeners</h3>
          <h4 class="stat-header text-center">
            <%= @podcast.subscribers * 3 %>
          </h4>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3 class="body-header text-center">Subscribed</h3>
          <h4 class="stat-header text-center">
            <% if @podcast.subscribers == 0 %>
              <small>No data</small>
            <% else %>
              <%= '%.2f' % ((1- (@podcast.subscribers.to_f/@podcast.average.to_f)) * 100) %>%
            <% end %>
          </h4>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3 class="body-header text-center">Not Subscribed</h3>
          <h4 class="stat-header text-center">
            <% if @podcast.subscribers == 0 %>
              <small>No data</small>
            <% else %>
              <%= '%.2f' % ((@podcast.subscribers.to_f/@podcast.average.to_f) * 100) %>%
            <% end %>
          </h4>
        </div>
      </div>
    </div>

<% end %>

  <% unless params[:name].present? %>

    <br />
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="body-header">Unique Listeners</h3>
          </div>
          <div class="panel-body">
            <ol>
              <% @subscribers.each do |a| %>
                <small><li style="margin-left: -20px;"><strong><%= link_to a.title.to_s, analytics_path + "?utf8=✓&name=" + a.title.to_param %> <span class="pull-right"><%= a.subscribers * 3 %></span></strong></li></small>
              <% end %>
            </ol>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="body-header">Average Per Episode</h3>
          </div>
          <div class="panel-body">
            <ol>
              <% @average.each do |a| %>
                <small><li style="margin-left: -20px;"><strong><%= link_to a.title.to_s, analytics_path + "?utf8=✓&name=" + a.title.to_param %> <span class="pull-right"><%= a.average.to_s %></span></strong></li></small>
              <% end %>
            </ol>
          </div>
        </div>
      </div>

  <% end %>

</div>

app/views/pages/people.html.erb
<% meta_title "People | The Nerdy Legion Podcast Network" %>

<div class="col-md-12 col-sm-12 col-xs-12">
  <% @users.each do |u| %>
    <div class="col-md-6 col-sm-12 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-md-5 col-sm-5 col-xs-12">
            <% if u.imageurl? %>
              <%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/loading.gif", data: { src: u.imageurl.to_s }, alt: u.name, width: "100%;", style: "height: 180px" %>
            <% else %>
              <%= image_tag "https://nl1.nyc3.digitaloceanspaces.com/assets/loading.gif", data: { src: "https://nl1.nyc3.digitaloceanspaces.com/assets/nouserlogo.gif" }, alt: u.name, width: "100%;", style: "height: 180px" %>
            <% end %>
          </div>
          <div class="col-md-7 col-sm-7 col-xs-12">
            <h4><%= u.name %></h4>
            <strong>Podcasts: </strong>
                <% if Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).count > 2 %>
                  <% Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).order(title: :asc).each do |p| %>
                      <% if p == Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).order(title: :asc).last %>
                        and
                        <%= link_to p, title: p.title do %>
                          <%= p.title.to_s %>
                        <% end %>
                      <% else %>
                        <%= link_to p, title: p.title do %>
                          <%= p.title.to_s + "," %>
                        <% end %>
                      <% end %>
                  <% end %>
                  <% elsif Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).count == 2 %>
                    <% Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).order(title: :asc).each do |p| %>
                        <% if p == Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).order(title: :asc).last %>
                          and
                          <%= link_to p, title: p.title do %>
                            <%= p.title.to_s %>
                          <% end %>
                        <% else %>
                          <%= link_to p, title: p.title do %>
                            <%= p.title.to_s %>
                          <% end %>
                        <% end %>
                    <% end %>
                <% else %>
                  <% Podcast.where(user_id: u.id).or(Podcast.where(user2_id: u.id)).or(Podcast.where(user3_id: u.id)).or(Podcast.where(producer_id: u.id)).order(title: :asc).each do |p| %>
                    <%= link_to p, title: p.title do %>
                      <%= p.title.to_s %>
                    <% end %>
                  <% end %>
              <% end %>
            <br />
            <br />
            <% if u.twitter? %>
              <%= link_to "Follow me on Twitter!", "https://www.twitter.com/" + u.twitter, class: "btn btn-info btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/robots.text.erb
<% if Rails.env.production? %>
  User-Agent: *
  Allow: /
  Disallow: /login
  Disallow: /analytics
  Disallow: /episodes/new
  Disallow: /episodes/edit
  Disallow: /podcasts/new
  Disallow: /podcasts/edit
  Disallow: /pending
  Disallow: /sidekiq
  Disallow: /edit
  Sitemap: <%= root_url %>/sitemap.xml
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/pages/subscribe.html.erb
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="body-header">
        Subscription Options
      </h4>
    </div>
    <div class="panel-body">
      <p class="hidden-xs">Enjoy the shows? Then why not subscribe? Below you'll find different ways to get your favorite Nerdy Legion podcasts which are all available in different platforms such as Apple Podcasts, Google Play, Sticher and TuneIn or the good old fashioned way via an RSS feed.</p>
      <p>If you want to subscribe to all the shows, feel free subscribe to the network feed via <%= link_to "RSS feed", "https://nerdylegion.com/episodes.rss" %>, <%= link_to "Apple Podcasts", "https://itunes.apple.com/us/podcast/nerdy-legion-podcast-network/id1041737614?mt=2", title: "Apple Podcasts" %> or <%= link_to "Google Play", "https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/I6eibh62qp5pxtioxui5d36nkem?t%3DNerdy_Legion_Podcast_Network%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16", title: "Google Play" %>.</p>
      <% @podcasts.each do |p| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <h5 class="body-header">
              <%= link_to p.title.to_s, p, title: p.title.to_s %>
            </h5>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="pull-left col-md-2 col-sm-3 col-xs-5" style="padding: 10px 15px 5px 0;">
                  <%= image_tag p.logourl.to_s, alt: p.title.to_s, width: "100%" %>
                </div>
                <p style="margin-top: 5px;"><%= p.title.to_s %> is hosted by
                  <% User.where(id: p.user_id).each do |host| %>
                    <%= link_to host.name.to_s, "https://www.twitter.com/" + host.twitter.to_s, title: host.name.to_s + " on Twitter", target: "_blank", rel: "noopener" %>
                  <% end %>
                  <% if p.user2_id? && p.user3_id.blank? %>
                    <% User.where(id: p.user2_id).each do |host2| %>
                      and <%= link_to host2.name.to_s, "https://www.twitter.com/" + host2.twitter.to_s, title: host2.name.to_s + " on Twitter", target: "_blank", rel: "noopener" %>
                    <% end %>
                  <% end %>
                  <% if p.user2_id? && p.user3_id? %>
                    <% User.where(id: p.user2_id).each do |host2| %>
                      , <%= link_to host2.name.to_s, "https://www.twitter.com/" + host2.twitter.to_s, title: host2.name.to_s + " on Twitter", target: "_blank", rel: "noopener" %>
                    <% end %>
                    <% User.where(id: p.user3_id).each do |host3| %>
                      and <%= link_to host3.name.to_s, "https://www.twitter.com/" + host3.twitter.to_s, title: host3.name.to_s + " on Twitter", target: "_blank", rel: "noopener" %>
                    <% end %>
                  <% end %>
                  <% User.where(id: p.producer_id).each do |producer| %>
                    and produced by <%= link_to producer.name.to_s, "https://www.twitter.com/" + producer.twitter.to_s, title: producer.name.to_s + " on Twitter", target: "_blank", rel: "noopener" %>.
                  <% end %>
                <ul class="list-inline">
                  <li style="margin-left: -5px;"><strong>Subscribe:</strong></li>
                  <% if p.itunes? %>
                    <li><%= link_to p.itunes, target: "_blank", rel: "noopener" do %>
                      Apple Podcasts<% end %></li>
                  <% end %>
                  <% if p.google? %>
                    <li><%= link_to p.google, target: "_blank", rel: "noopener" do %>
                      Google Play<% end %></li>
                  <% end %>
                  <% if p.spotify? %>
                    <li><%= link_to p.spotify, target: "_blank", rel: "noopener" do %>
                      Spotify<% end %></li>
                  <% end %>
                  <% if p.stitcher? %>
                    <li><%= link_to p.stitcher, target: "_blank", rel: "noopener" do %>
                      Stitcher<% end %></li>
                  <% end %>
                  <% if p.tunein? %>
                    <li><%= link_to p.tunein, target: "_blank", rel: "noopener" do %>
                      TuneIn<% end %></li>
                  <% end %>
                  <% if p.youtube? %>
                    <li><%= link_to p.youtube, target: "_blank", rel: "noopener" do %>
                      YouTube<% end %></li>
                  <% end %>
                  <li><%= link_to root_url + "podcasts/" + p.slug.to_s + ".rss" do %>
                    RSS<% end %></li>
                </ul>
                <p><%= strip_tags(p.description.html_safe) %> <%= p.title.to_s %> has released <strong><%= p.episodes.count %> episodes</strong> since launching on <%= p.created_at.strftime("%b %m, %Y") %>.</p>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/user_admin_new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
    <h4 class="text-center">Create New User</h4>
    <%= form_tag controller: 'pages', action: 'create_user', method: :post, remote: true do %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="nameAddon"><i class="fa fa-users"></i></span>
            <%= text_field_tag :name, nil, placeholder: "Enter a name", class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="emailAddon"><i class="fa fa-envelope"></i></span>
            <%= email_field_tag :email, nil, placeholder: "Enter an email address", class: "form-control" %>
          </div>
        </div>
        <div class="input-group">
          <span class="input-group-addon" id="twitterAddon">@</span>
          <%= text_field_tag :twitter, nil, placeholder: "Twitter handle (No @ symbol)", class: "form-control" %>
        </div>
        <br />
        <div class="form-group">
          <em>Passwords have a six character minimum</em>
          <br />
          <div class="input-group">
            <span class="input-group-addon" id="passwordAddon"><i class="fa fa-key"></i></span>
            <%= password_field_tag :password, nil, placeholder: "Enter a password", class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon" id="password_confirmationAddon"><i class="fa fa-key"></i></span>
            <%= password_field_tag :password_confirmation, nil, placeholder: "Please confirm password", class: "form-control" %>
        </div>
        <br />
        <div class="form-group">
          <%= submit_tag "Create User", class: "btn btn-primary btn-sm form-control" %>
        </div>
    <% end %>
    <div class="clearfix"></div>
  </div>
</div>