config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :sponsors
  resources :settings
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }, via: :get
  end

  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web, at: '/sidekiq', as: :sidekiq
  end

  namespace :pages do
    get "allpodcasts"
    get "locations"
    get "platforms"
    get "timeofday"
    get "downloads"
  end

  resources :abouts
  resources :privacies
  resources :terms
  resources :episodes
  get 'pending' => 'episodes#pending', as: :pending
  resources :podcasts
  get 'search' => 'search#search'
  get 'shows/acp' => redirect('/podcasts/acp')
  get 'shows/boomaddiction' => redirect('/podcasts/ba')
  get 'shows/cbw' => redirect('/podcasts/cbw')
  get 'shows/collectingvaliant' => redirect('/podcasts/cv')
  get 'shows/iamgotham' => redirect('/podcasts/iag')
  get 'shows/nerdylegion' => redirect('/podcasts/nl')
  get 'shows/pth' => redirect('/podcasts/pth')
  get 'shows/rb' => redirect('/podcasts/rb')
  get 'podcasts/rb' => redirect('/podcasts/absolutedc')
  get 'podcasts/pth' => redirect('/podcasts/wrestlinginsomniac')
  get 'shows/marvelpodcast' => redirect('/podcasts/ump')
  get 'shows/vcp' => redirect('/podcasts/vcp')
  get 'shows/whatdidyouwatchthisweek' => redirect('/podcasts/wdyw')
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callback" }, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup'}
  root :to => 'episodes#index'
  get "aboutus" => 'abouts#index', as: :aboutus
  get 'privacy' => 'privacies#index', as: :privacypolicy
  get 'terms' => 'terms#index', as: :termsofservice
  get 'subscribe' => 'pages#subscribe', as: :subscribe
  get 'user_admin' => 'pages#user_admin', as: :user_admin
  get 'user_admin_new_path' => 'pages#user_admin_new', as: :user_admin_new
  resource :pages do
    member do
      post :create_user
      post :destroy_user
      post :podcaster_true
      post :podcaster_false
      post :analytics_true
      post :analytics_false
      post :admin_true
      post :admin_false
    end
  end
  get 'analytics' => 'pages#analytics', as: :analytics
  get 'sitemap.xml', :to => 'pages#sitemap', :defaults => { :format => 'xml' }
  get 'robots.:format' => 'pages#robots'
  get '*path' => redirect('/')
end

app/views/layouts/_footer.html.erb
<div class="clearfix"><br /></div>
<nav class="navbar navbar-footer">
  <div class="container-fluid">
    <div class="navbar-footer text-center">
      <ul class="list-inline small">
        <% if Setting.count > 0 %>
          <% if Setting.first.twitter? %>
            <li><%= link_to "https://www.twitter.com/" + Setting.first.twitter.to_s, title: "Follow us on Twitter" do %><i class="fa fa-twitter"></i><% end %></li>
          <% end %>
          <% if Setting.first.facebook? %>
            <li><%= link_to Setting.first.facebook.to_s, title: "Follow us on Facebook" do %><i class="fa fa-facebook"></i><% end %></li>
          <% end %>
          <% if Setting.first.instagram? %>
            <li><%= link_to Setting.first.instagram.to_s, title: "Follow us on Instagram" do %><i class="fa fa-instagram"></i><% end %></li>
          <% end %>
          <% if Setting.first.twitch? %>
            <li><%= link_to Setting.first.twitch.to_s, title: "Follow us on Twitch" do %><i class="fa fa-twitch"></i><% end %></li>
          <% end %>
        <% end %>
        <% if Privacy.all.count == 1 %>
          <li><%= link_to "Privacy", privacypolicy_path, title: "Privacy Policy" %></li>
        <% else %>
          <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "Create Privacy Policy", new_privacy_path, title: "Create Privacy Policy" %></li>
          <% end %>
        <% end %>
        <% if Term.all.count == 1 %>
          <li><%= link_to "Terms", termsofservice_path, title: "Terms of Service" %></li>
        <% else %>
          <% if user_signed_in? && current_user.admin? %>
            <li><%= link_to "Create Terms of Service", new_term_path, title: "Create Terms of Service" %></li>
          <% end %>
        <% end %>
        <% unless user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path, title: "Login" %></li>
        <% end %>
        <br />
        <% if Setting.count > 0 %>
          <small><%= Setting.first.name.to_s %> &copy; <%= Time.now.strftime("%Y") %></small>
        <% else %>
          Powered by Sprout
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header.amp.erb
<h1><a href="/" title="Nerdy Legion">Nerdy Legion</a></h1>

app/views/layouts/_header.html.erb
<div class="bs-docs-section clearfix">
        <div class="row">
          <div class="col-lg-12">

            <div class="bs-component">
              <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <% if Setting.count > 0 && Setting.first.name? %>
                      <h1 class="navbar-header">
                        <%= link_to $setting.name.to_s, root_url, title: $setting.name.to_s, class: "navbar-brand" %></h1>
                    <% else %>
                      <h1 class="navbar-header"><a class="navbar-brand" href="/" title="Sprout">Sprout</a></h1>
                    <% end %>
                  </div>

                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-links">
                      <li class="dropdown show">
                        <a class="dropdown-toggle" href="#" id="dropdownMenuLink" title="Podcasts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Podcasts <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                          <% @podcasts = Podcast.where(status: "Published").order(title: :asc) %>
                          <% @podcasts.each do |p| %>
                            <li>
                              <%= link_to p, title: p.title, "data-turbolinks" => "false" do %>
                                <%= p.title %>
                              <% end %>
                            </li>
                          <% end %>

                          <% @archived = Podcast.where(status: "Archived").order(title: :asc) %>
                            <% if @archived.count > 0 %>
                            <li class="divider"></li>
                              <li class="dropdown-submenu">
                                <a tabindex="-1" href="#" title="Archived Shows">Archived Shows</a>
                                <ul class="dropdown-menu">
                                  <% @archived.each do |p| %>
                                    <li>
                                      <%= link_to p, title: p.title, "data-turbolinks" => "false" do %>
                                        <%= p.title %>
                                      <% end %>
                                    </li>
                                  <% end %>
                                </ul>
                              </li>
                            <% end %>
                        </ul>
                      </li>
                      <li>
                        <% if About.all.count == 1 %>
                          <%= link_to "About", aboutus_path, title: "About Us" %>
                        <% else %>
                          <% if user_signed_in? && current_user.admin? %>
                            <%= link_to "Create About", new_about_path, title: "Create About" %>
                          <% end %>
                        <% end %>
                      </li>
                      <li><%= link_to "Subscribe", subscribe_path, title: "Subscribe" %></li>
                      <% if Setting.count > 0 && Setting.first.merch? %>
                        <li><%= link_to "Merch", Setting.first.merch.to_s, target: "_blank", rel: "noopener", title: "Merch" %></li>
                      <% end %>
                      <% unless user_signed_in? %>
                        <li class="visible-xs"><%= link_to "Login", new_user_session_path, target: "_blank", rel: "noopener", title: "Login" %></li>
                      <% end %>
                      <% if user_signed_in? %>
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle visible-sm" data-toggle="dropdown" role="button" aria-expanded="false" title="Admin"><i class="fa fa-dashboard"></i> <span class="caret"></span></a>
                            <a href="#" class="dropdown-toggle hidden-sm" data-toggle="dropdown" role="button" aria-expanded="false" title="Admin">Administration <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                              <li><%= link_to "Analytics", analytics_path, title: "Analytics", "data-turbolinks" => "false" if current_user.analytics? %></li>
                              <li><%= link_to "New Episode", new_episode_path, title: "New Episode", "data-turbolinks" => "false" if current_user.podcaster? %></li>
                              <li><%= link_to "New Podcast", new_podcast_path, title: "New Podcast", "data-turbolinks" => "false" if current_user.admin? %></li>
                              <li><%= link_to "Pending Episodes", pending_path, title: "View pending episodes", "data-turbolinks" => "false" if current_user.podcaster? %></li>
                              <% if current_user.admin? %>
                                <li><%= link_to "Sidekiq Queue", sidekiq_path, title: "Sidekiq Queue", "data-turbolinks" => "false" %></li>
                                <% if $settings_exist %>
                                  <li><%= link_to "Site Settings", edit_setting_path(Setting.find(1)), title: "Site Settings", "data-turbolinks" => "false" %></li>
                                <% else %>
                                  <li><%= link_to "Site Settings", new_setting_path, title: "Site Settings", "data-turbolinks" => "false" %></li>
                                <% end %>
                                <li><%= link_to "Sponsors", sponsors_path, title: "Sponsors", "data-turbolinks" => "false" %></li>
                                <li><%= link_to "Users", user_admin_path, title: "User Administration", "data-turbolinks" => "false" %></li>
                              <% end %>
                              <li class="text-center">-------------------------------</li>
                              <li><%= link_to "Edit Profile", edit_user_registration_path, title: "Edit profile" %></li>
                              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, title: "Logout" %></li>
                            </ul>
                          </li>
                      <% end %>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <li class="col-md-9 col-sm-8 col-xs-6">
                        <%= form_with url: search_path, local: true, method: :get, html: { id: "search_form" } do |form| %>
                          <%= form.text_field :q, placeholder: "Search", data: { behavior: "autocomplete" }, class: "form-control", id: "autocomplete" %>
                          <%= submit_tag "", id: "submit_search", style: "display: none;" %>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>

          </div>
        </div>
      </div>

app/views/layouts/application.amp.erb
<!doctype html>
<html amp lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="canonical" href="<%= url_for(format: :html, only_path: false) %>" >
    <link rel="amphtml" href="<%= url_for(format: :amp, only_path: false) %>" >
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "url": "https://nerdylegion.com",
      "image": "https://nl1.nyc3.digitaloceanspaces.com/assets/nloffline.jpg",
      "description": "The Nerdy Legion podcast network is a place for people obsessed with geek culture with topics ranging from comics, TV, movies, wrestling and more.",
      "contactPoint": [
        { "@type": "ContactPoint",
          "url": "https://nerdylegion.com",
          "contactType": "customer service"
        }
      ],
      "sameAs": [
        "https://www.facebook.com/nerdylegion",
        "https://www.twitter.com/nerdylegion"
      ]
    }
    </script>
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
    <style amp-custom>.amp{margin: 5px;}h1{font-size: 1.25em; border: 1px solid #95a5a6; padding: 5px;}h1 a{text-decoration: none; color: #c0392b;}h2{font-size: 1.1em; margin: 0;}h2 a{color: #c0392b; text-decoration: none;}button{width: 100%; background-color: #c0392b; color: white; padding: 5px;}button a{color: white; text-decoration: none;}h5{margin: 3px 0px 0 0; color: #95a5a6; font-size: 0.75em;}</style>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-audio" src="https://cdn.ampproject.org/v0/amp-audio-0.1.js"></script>
  </head>
  <body>
    <div class="amp">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#" lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="fXdxoXSNBjFWM75hh3nn9wm4O6FsX2DgEQO1qTpgfy4" />
    <meta name="twitter:card" content="summary_large_image" />
    <% if $settings_exist %>
      <meta name="twitter:site" content="@<%= $setting.twitter.to_s %>" />
      <meta name="twitter:creator" content="@<%= $setting.twitter.to_s %>" />
    <% end %>
    <% if yield(:twitter_image).present? %>
      <meta property="twitter:image" content="<%= yield(:og_image) %>" />
      <meta property="twitter:image:type" content="image/jpeg" />
    <% else %>
      <meta property="twitter:image" content="https://nl1.nyc3.digitaloceanspaces.com/assets/nloffline.jpg" />
      <meta property="twitter:image:type" content="image/jpeg" />
    <% end %>
    <% if yield(:og_title).present? %>
      <meta name="twitter:title" content="<%= yield(:og_title) %>" />
    <% else %>
      <% if $settings_exist %>
        <meta name="twitter:title" content="<%= $setting.name.to_s %>" />
      <% else %>
        <meta name="twitter:title" content="Sprout" />
      <% end %>
    <% end %>
    <% if yield(:og_description).present? %>
      <meta name="twitter:description" content="<%= yield(:og_description) %>" />
    <% else %>
      <% if $settings_exist %>
        <meta name="twitter:description" content="<%= strip_tags($setting.description.to_s.html_safe) %>" />
      <% else %>
        <meta name="twitter:description" content="Powered by Sprout, an open source solution for creating and distributing podcasts" />
      <% end %>
    <% end %>
    <% if yield(:meta_description).present? %>
      <meta name="description" content="<%= yield(:meta_description) %>" />
    <% else %>
      <% if $settings_exist %>
        <meta name="description" content="<%= strip_tags($setting.description.to_s.html_safe) %>" />
        <meta name="keywords" content="<%= $setting.keywords.to_s %>" />
      <% else %>
        <meta name="description" content="Powered by Sprout, an open source solution for creating and distributing podcasts" />
      <% end %>
    <% end %>
    <% if yield(:og_title).present? %>
      <meta property="og:title" content="<%= yield(:og_title) %>" />
    <% else %>
      <% if $settings_exist %>
        <meta property="og:title" content="<%= strip_tags($setting.description.to_s.html_safe) %>" />
      <% else %>
        <meta property="og:title" content="Powered by Sprout, an open source solution for creating and distributing podcasts" />
      <% end %>
    <% end %>
    <% if yield(:og_description).present? %>
      <meta property="og:description" content="<%= yield(:og_description) %>" />
    <% else %>
      <% if $settings_exist %>
        <meta name="og:description" content="<%= strip_tags($setting.description.to_s.html_safe) %>" />
      <% else %>
        <meta name="og:description" content="Powered by Sprout, an open source solution for creating and distributing podcasts" />
      <% end %>
    <% end %>
    <% if yield(:og_type).present? %>
      <meta property="og:type" content="<%= yield(:og_type) %>" />
    <% else %>
      <meta property="og:type" content="website" />
    <% end %>
    <% if yield(:og_audio).present? %>
      <meta property="og:audio" content="<%= yield(:og_audio) %>" />
      <meta property="og:audio:type" content="audio/mpeg" />
    <% end %>
    <% if yield(:og_url).present? %>
      <meta property="og:url" content="<%= yield(:og_url) %>" />
    <% else %>
      <meta property="og:url" content="<%= root_url %>" />
    <% end %>
    <% if yield(:og_image).present? %>
      <meta property="og:image" content="<%= yield(:og_image) %>" />
      <meta property="og:image:type" content="image/jpeg" />
      <meta property="og:image:width" content="350" />
      <meta property="og:image:height" content="350" />
    <% else %>
      <meta property="og:image" content="https://nl1.nyc3.digitaloceanspaces.com/assets/nloffline.jpg" />
      <meta property="og:image:type" content="image/jpeg" />
    <% end %>
    <% if $settings_exist %>
      <meta property="og:site_name" content="<%= $setting.name.to_s %>" />
    <% else %>
      <meta property="og:site_name" content="Sprout" />
    <% end %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#eb6864" />
    <%= csrf_meta_tags %>
    <% if $settings_exist %>
      <link rel="shortcut icon" type="image/x-icon" href="<%= $setting.favicon.to_s %>" />
    <% end %>
    <link rel="canonical" href="<%= root_url %>" />
    <% if yield(:meta_title).present? %>
      <title><%= yield(:meta_title) %></title>
    <% else %>
      <% if $settings_exist %>
        <title><%= $setting.name.to_s %> | <%= $setting.title.to_s %></title>
      <% else %>
        <title>Sprout | This website is powered by Sprout</title>
      <% end %>
    <% end %>
    <%= stylesheet_link_tag 'application', :media => "all" %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <% if controller_name == "pages" && action_name == "analytics" %>
      <%= javascript_include_tag "//www.google.com/jsapi" %>
      <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", "chartkick" %>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: Rails.env.production?, defer: true %>

    <link rel="manifest" href="/manifest.json" />
  </head>

  <% if request.path_info.include?('new') %>
    <body class="container">
  <% elsif request.path_info.include?('edit') %>
    <body class="container">
  <% elsif request.path_info.include?('about') %>
    <body class="container">
  <% elsif request.path_info.include?('people') %>
    <body class="container">
  <% elsif request.path_info.include?('pending') %>
    <body class="container">
  <% elsif request.path_info.include?('analytics') %>
    <body class="container">
  <% elsif request.path_info.include?('users') %>
    <body class="container">
  <% elsif controller_name == "episodes" && action_name == "index" %>
    <body class="container">
  <% else %>
    <body class="container track_body" %>
  <% end %>

    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <div id="notice_wrapper">
        <% if name == "alert" %>
          <div class="alert alert-danger alert-dismissible alert-message" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= msg %>
          </div>
        <% else %>
          <div class="alert alert-success alert-dismissible alert-message" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= msg %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <% if $settings_exist %>
      <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "Organization",
        "url": "<%= root_url %>",
        "image": "https://nl1.nyc3.digitaloceanspaces.com/assets/nloffline.jpg",
        "description": "<%= $setting.description.to_s.html_safe %>",
        "contactPoint": [
          { "@type": "ContactPoint",
            "url": "<%= root_url %>",
            "contactType": "customer service"
          }
        ],
        "sameAs": [
          "<%= $setting.facebook.to_s %>",
          "https://www.twitter.com/<%= $setting.twitter.to_s %>"
        ]
      }
      </script>
    <% end %>
  </body>


</html>